@extends('layouts.app')
@section('title','Ưu đãi doanh nghiệp')
@section('content')
<section class="dashboard-card"><a href="{{ route('salon.branches') }}">← Chi nhánh</a><h1>Ưu đãi doanh nghiệp</h1><p>Mã dùng chung các chi nhánh của doanh nghiệp. Lịch hủy, bị từ chối hoặc hết hạn được trả lượt. Múi giờ: {{ config('app.timezone') }}.</p><x-errors />
<form method="post" action="{{ route('vouchers.store',$branch) }}" data-submit-form>@csrf
<div class="row g-3">
@foreach(['code'=>'Mã ưu đãi','name'=>'Tên ưu đãi'] as $field=>$label)<div class="col-md-6"><label for="{{ $field }}">{{ $label }}</label><input class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field) }}" maxlength="{{ $field==='code'?50:200 }}" required></div>@endforeach
<div class="col-md-6"><label for="discount_type">Loại giảm</label><select class="form-control" id="discount_type" name="discount_type"><option value="PERCENTAGE" @selected(old('discount_type')==='PERCENTAGE')>Phần trăm</option><option value="FIXED_AMOUNT" @selected(old('discount_type')==='FIXED_AMOUNT')>Số tiền cố định (₫)</option></select></div>
@foreach(['discount_value'=>'Giá trị giảm','min_order_value'=>'Giá trị đơn tối thiểu (₫)','max_discount'=>'Giảm tối đa (₫, có thể bỏ trống)','total_quantity'=>'Tổng số lượt','max_usage_per_customer'=>'Số lượt mỗi khách'] as $field=>$label)<div class="col-md-6"><label for="{{ $field }}">{{ $label }}</label><input type="number" step="{{ in_array($field,['total_quantity','max_usage_per_customer'])?'1':'0.01' }}" min="0" class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$field==='min_order_value'?0:($field==='max_usage_per_customer'?1:'')) }}" @required($field!=='max_discount')></div>@endforeach
@foreach(['start_date'=>'Bắt đầu','end_date'=>'Kết thúc'] as $field=>$label)<div class="col-md-6"><label for="{{ $field }}">{{ $label }}</label><input type="datetime-local" class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field) }}" required></div>@endforeach
</div><button class="btn btn-primary mt-3" data-submit-button><span data-button-label>Tạo ưu đãi</span><span class="button-spinner" aria-hidden="true" hidden></span></button><p role="status" data-submit-status></p></form>
<div class="table-responsive mt-4"><table class="table"><thead><tr><th>Mã</th><th>Ưu đãi</th><th>Lượt đã giữ/dùng</th><th>Trạng thái</th></tr></thead><tbody>@forelse($vouchers as $voucher)<tr><td>{{ $voucher->code }}</td><td>{{ $voucher->name }}<br>{{ $voucher->discount_value }} {{ $voucher->discount_type==='PERCENTAGE'?'%':'₫' }}</td><td>{{ $voucher->used_quantity }}/{{ $voucher->total_quantity }}</td><td>{{ $voucher->status }}<form method="post" action="{{ route('vouchers.toggle',[$branch,$voucher]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $voucher->status==='ACTIVE'?'INACTIVE':'ACTIVE' }}"><button class="btn btn-sm">{{ $voucher->status==='ACTIVE'?'Tạm ngừng':'Kích hoạt' }}</button></form></td></tr>@empty<tr><td colspan="4">Chưa có ưu đãi.</td></tr>@endforelse</tbody></table></div>{{ $vouchers->links() }}</section>
@endsection
